spring:
  profiles: local
  datasource:
    sql-script-encoding: UTF-8
    initialization-mode: always
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:./data/blog
      username: sa
      password:
  h2:
    console:
      enabled: true
      path: /h2_console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  devtools:
    restart:
      enabled: true

jwt:
  header: Authorization
  secret: aHR0cHM6Ly9naXRodWIuY29tL2poamhqMDM2Ni9ibG9nLXNlYXJjaC1zZXJ2aWNl
  token-validity-in-seconds: 86400

logging:
  level:
    com.search: DEBUG